export enum StatusCode {
    REGISTER_SUCCESS,
    REGISTER_ACCOUNT_ALREADY_EXISTS,
    REGISTER_PASSWORD_INVALID,
    REGISTER_USERNAME_INVALID,
    LOGIN_DOESNT_EXIST,
    LOGIN_WRONG_PASSWORD,
    LOGIN_SUCCESS
}